name: "VSCode Publish"

on:
  push:
    branches:
      - main

jobs:
  check_version:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./vscode
    outputs:
      version: ${{ steps.version.outputs.version }}
      alpha: ${{ steps.version.outputs.alpha }}
      validVersion: ${{ steps.version.outputs.validVersion }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Package Version
        id: version
        uses: actions/github-script@v7
        with:
          script: |
            console.log(process.cwd());
            const fs = require('fs');
            const manifest = JSON.parse(fs.readFileSync('package.json', 'utf8'));
            const version = manifest.version;
            core.setOutput('version', version);
            const alpha = version.includes('alpha');
            core.setOutput('alpha', alpha || '');
            const validVersion = /^\d+\.\d+\.\d+$/.test(version);
            core.setOutput('validVersion', validVersion || '');
            return {
              version,
              alpha,
              validVersion
            };

      - name: Display Info
        uses: streetsidesoftware/actions/public/summary@v1
        with:
          text: |
            # Package Info
            version: `${{ steps.version.outputs.version }}`
            alpha: ${{ contains(steps.version.outputs.version, 'alpha') }}
            validVersion: ${{ steps.version.outputs.validVersion }}
            versionInfo: ${{ toJSON(steps.version.outputs) }}

      - name: Check Version
        if: ${{ steps.version.outputs.validVersion != 'true' }}
        run: |
          echo "::warning title=Do NOT Publish::The version in package.json is not a releasable version."

  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vscode
    needs: check_version
    if: ${{ needs.check_version.outputs.validVersion == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Install
        run: |
          npm install

      - name: Publish extension to marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          registryUrl: https://marketplace.visualstudio.com

          # Personal access token
          pat: ${{secrets.PERSONAL_ACCESS_TOKEN}}
